### ISSUE TITLE
As a user I would like to have a guide to use Nachet

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/nachet#40]
## Context

As Nachet is progressing with an increase in its volume of features, it becomes as more important to help a user navigate throughout the application.

## Acceptance Criteria

1. There is a brief section about Nachet's mission.
2. The core features of Nachet are explained with diverse media tool (picture, GIF, video)
3. An average user should be able to use Nachet with the knowledge of its functionality

## TODO

- [ ] ai-cfia/nachet-frontend#164
- [ ] Create a direct link on the Nachet's app towards the user guide
- [ ] Create a "tutorial" for first time user on Nachet's interface.
